### PR TITLE
Modified navbar

### PR DESCRIPTION
**Pull request by sul1106**

### CODE REVIEW

**Comment by sul1106** [comment]
Please check this...Added hamburger menu and made it responsive

**Comment by ScreenTechnicals** [comment]
> Please check this...Added hamburger menu and made it responsive

please resolve the conflicts so that I can merge it !!

**Comment by sul1106** [comment]
Are there any more conflicts?

**Comment by sul1106** [comment]
Please check

**Comment by ScreenTechnicals** [comment]
> Please check

please check the style.css

**Comment by sul1106** [comment]
hopefully no more 😭

**Pull request merged**
